version: "3.5"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /var/andrferr/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /var/andrferr/data/mariadb
      o: bind
      type: none
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 433:433
    restart: always
    networks:
      - network
    volumes:
      - wordpress:/var/www/html

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    restart: always
    env_file: .env
    networks:
      - network
    volumes:
     - wordpress:/var/www/html
    
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - network

networks:
  network:
    driver: "bridge"

    