version: "3.5"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /var/andrferr/data/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /var/andrferr/data/mariadb
      o: bind
      type: none

networks:
  network:
    name: inception-network
    driver: "bridge"


services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:andrferr
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    restart: always
    networks:
      - network
    volumes:
      - wordpress:/var/www/html

  wordpress:
    container_name: wordpress
    image: wordpress:andrferr
    depends_on:
      - mariadb
    build: ./requirements/wordpress/.
    restart: always
    env_file:
      - .env
    networks:
      - network
    volumes:
     - wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:andrferr
    restart: always
    env_file:
      - .env
    networks:
      - network
    volumes:
      - mariadb:/var/lib/mysql
